[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "clean_data"
author = "Sem"
author-email = "cloudtimewater@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]

